import { Property } from './types';

export const PROPERTIES: Property[] = [
    {
        id: '1',
        title: 'Luxury 3-Bedroom Ocean View Apartment',
        address: '15 Admiralty Way, Lekki Phase 1',
        location: 'Lekki',
        price: 150000000, // 150M Naira
        currency: 'NGN',
        type: 'Apartment',
        bedrooms: 3,
        bathrooms: 4,
        sizeSqft: 2200,
        imageUrl: '/images/luxury_apartment.png',
        images: [
            '/images/luxury_apartment.png',
            'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2580&auto=format&fit=crop',
        ],
        isVerified: true,
        status: 'Verified',
        rating: 4.8,
        amenities: ['Ocean View', 'Swimming Pool', '24/7 Power', 'Gym', 'Security'],
        description: 'Experience the pinnacle of luxury living in this stunning 3-bedroom apartment with panoramic ocean views. Located in the heart of Lekki Phase 1, this property features premium finishes, a state-of-the-art kitchen, and access to exclusive world-class amenities.',
        coordinates: { lat: 6.4500, lng: 3.4800 },
        addedAt: '2026-01-15T10:00:00Z',
        developer: {
            name: 'Eko Atlantic Developers',
            isVerified: true
        },
        tags: ['New', 'Open house today']
    },
    {
        id: '2',
        title: 'Modern 4-Bedroom Semi-Detached Duplex',
        address: 'Blue Water Estate, Ikate',
        location: 'Ikate',
        price: 220000000, // 220M Naira
        currency: 'NGN',
        type: 'House',
        bedrooms: 4,
        bathrooms: 5,
        sizeSqft: 3500,
        imageUrl: 'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?q=80&w=2670&auto=format&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1628624747186-a941c476b7ef?q=80&w=2670&auto=format&fit=crop',
        ],
        isVerified: true,
        status: 'Verified',
        rating: 4.6,
        amenities: ['Gated Estate', 'BQ', 'Fitted Kitchen', 'Parking'],
        description: 'A contemporary mastery of design. This 4-bedroom duplex offers spacious living areas, high ceilings, and a fully fitted kitchen. Located in a secure, family-friendly estate.',
        coordinates: { lat: 6.4400, lng: 3.5000 },
        addedAt: '2026-02-01T09:30:00Z',
        developer: {
            name: 'Urban Shelter',
            isVerified: true
        },
        tags: ['New']
    },
    {
        id: '3',
        title: 'Minimalist Studio Loft',
        address: 'Victoria Island, Lagos',
        location: 'Victoria Island',
        price: 85000000,
        currency: 'NGN',
        type: 'Apartment',
        bedrooms: 1,
        bathrooms: 1,
        sizeSqft: 950,
        imageUrl: '/images/minimalist_loft.png',
        images: ['/images/minimalist_loft.png'],
        isVerified: true,
        status: 'Verified',
        rating: 4.9,
        amenities: ['Smart Home', 'Rooftop Lounge', 'Co-working Space'],
        description: 'Perfect for the modern professional. This studio loft in VI combines brutalist aesthetics with high-end comfort. Featuring concrete finishes and floor-to-ceiling windows.',
        coordinates: { lat: 6.4253, lng: 3.4219 },
        addedAt: '2026-02-03T14:15:00Z',
        developer: {
            name: 'Avant Garde Living',
            isVerified: true
        },
        tags: ['Price drop']
    },
    {
        id: '4',
        title: 'Exquisite 5-Bedroom Detached Villa',
        address: 'Banana Island, Ikoyi',
        location: 'Ikoyi',
        price: 850000000,
        currency: 'NGN',
        type: 'House',
        bedrooms: 5,
        bathrooms: 6,
        sizeSqft: 6000,
        imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2670&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2670&auto=format&fit=crop'],
        isVerified: true,
        status: 'Verified',
        rating: 5.0,
        amenities: ['Private Pool', 'Cinema', 'Elevator', 'Jetty Access'],
        description: 'The ultimate status symbol. A 5-bedroom detached villa in the most exclusive neighborhood in Nigeria. Unmatched privacy, luxury, and security.',
        coordinates: { lat: 6.4549, lng: 3.4246 },
        addedAt: '2025-12-20T11:00:00Z',
        developer: {
            name: 'Prestige Homes',
            isVerified: true
        },
        tags: ['For sale']
    },
    {
        id: '5',
        title: 'Prime Commercial Office Space',
        address: 'Herbert Macaulay Way, Yaba',
        location: 'Yaba',
        price: 450000000,
        currency: 'NGN',
        type: 'Office',
        bedrooms: 0,
        bathrooms: 2,
        sizeSqft: 4000,
        imageUrl: '/images/commercial_office.png',
        images: ['/images/commercial_office.png'],
        isVerified: true,
        status: 'Verified',
        rating: 4.5,
        amenities: ['Parking', 'Fiber Internet', 'Reception'],
        description: 'Strategically located in the tech hub of Lagos. This open-plan office space is ideal for growing startups or established firms looking for visibility.',
        coordinates: { lat: 6.5095, lng: 3.3711 },
        addedAt: '2026-02-04T08:00:00Z',
        developer: {
            name: 'TechHub Properties',
            isVerified: true
        }
    },
    {
        id: '6',
        title: 'Serviced 2-Bedroom Apartment',
        address: 'Chevron Drive, Lekki',
        location: 'Lekki',
        price: 90000000,
        currency: 'NGN',
        type: 'Apartment',
        bedrooms: 2,
        bathrooms: 3,
        sizeSqft: 1500,
        imageUrl: '/images/serviced_apartment.png',
        images: ['/images/serviced_apartment.png'],
        isVerified: true,
        status: 'Verified',
        rating: 4.7,
        amenities: ['Serviced', 'Gym', 'Pool'],
        description: 'Hassle-free living. Fully serviced apartment with 24/7 power and security. Ideal for small families or investors looking for rental income.',
        coordinates: { lat: 6.4380, lng: 3.5200 },
        addedAt: '2026-02-02T16:20:00Z',
        developer: {
            name: 'Lekki Gardens',
            isVerified: true
        },
        tags: ['New']
    },
    {
        id: '7',
        title: 'Plot of Land (600sqm)',
        address: 'Abijo GRA, Lekki-Epe Expressway',
        location: 'Abijo',
        price: 25000000,
        currency: 'NGN',
        type: 'Land',
        bedrooms: 0,
        bathrooms: 0,
        sizeSqft: 6458,
        imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=2832&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=2832&auto=format&fit=crop'],
        isVerified: true,
        status: 'Verified',
        rating: 4.4,
        amenities: ['Dry Land', 'C of O', 'Perimeter Fencing'],
        description: 'Build your dream home. Dry land in a fast-developing GRA with Certificate of Occupancy. Ready for immediate development.',
        coordinates: { lat: 6.4800, lng: 3.6000 },
        addedAt: '2026-01-10T12:00:00Z',
        developer: {
            name: 'LandWey',
            isVerified: true
        }
    },
    {
        id: '8',
        title: 'Contemporary Terrace Duplex',
        address: 'Orchid Road, Lekki',
        location: 'Lekki',
        price: 110000000,
        currency: 'NGN',
        type: 'House',
        bedrooms: 4,
        bathrooms: 4,
        sizeSqft: 2800,
        imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=2574&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=2574&auto=format&fit=crop'],
        isVerified: true,
        status: 'Verified',
        rating: 4.3,
        amenities: ['Smart Access', 'Play Area', 'Good Road Network'],
        description: 'Affordable luxury. This 4-bedroom terrace offers great value for money with modern finishings and good proximity to the expressway.',
        coordinates: { lat: 6.4450, lng: 3.5100 },
        addedAt: '2026-01-25T09:00:00Z',
        developer: {
            name: 'Veritasi Homes',
            isVerified: true
        },
        tags: ['Sold out']
    }
];
